name: Scrape Nobroker

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    # Run every day at 10:15am
    - cron: "15 10 * * *"

permissions:
  contents: write

jobs:
  scrape-nobroker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: node tools/scrape-nobroker.js
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Scrape NoBroker: ${{ github.sha }}'
