name: Scrape Housing.com

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    # Run every day at 10:30am
    - cron: "30 10 * * *"

permissions:
  contents: write

jobs:
  scrape-housing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: node tools/scrape-housing.js # generates data/housing.csv
      - run: |
          git add data/housing.csv
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git commit -m 'Build: ${{ github.sha }} (${{ github.event_name }})'
          git push origin data
